-- درج داده‌های نمونه پروژه
INSERT INTO projects (
  title,
  description,
  image_url,
  project_type,
  location,
  capacity,
  completion_date,
  client_name,
  features,
  gallery_images,
  slug,
  is_published
) VALUES 
(
  'نصب خورشیدی مسکونی - خانواده جانسون',
  'نصب کامل سیستم خورشیدی روی پشت‌بام برای یک خانه مدرن خانوادگی، ارائه انرژی پاک و صرفه‌جویی قابل توجه در هزینه‌ها.',
  '/placeholder.svg?height=400&width=600',
  'residential',
  'تهران، ایران',
  '8.5 کیلووات',
  '2024-03-15',
  'خانواده جانسون',
  ARRAY['پنل‌های تک کریستال با بازدهی بالا', 'تکنولوژی اینورتر هوشمند', 'سیستم پشتیبان باتری', 'نظارت از طریق اپلیکیشن موبایل', 'گارانتی 25 ساله'],
  ARRAY['/placeholder.svg?height=300&width=400', '/placeholder.svg?height=300&width=400'],
  'johnson-family-residential-solar',
  true
),
(
  'مزرعه خورشیدی تجاری - صنایع گرین‌تک',
  'نصب خورشیدی مقیاس بزرگ روی زمین برای تسهیلات تولیدی، کاهش هزینه‌های عملیاتی به میزان 60 درصد.',
  '/placeholder.svg?height=400&width=600',
  'commercial',
  'اصفهان، ایران',
  '250 کیلووات',
  '2024-01-20',
  'صنایع گرین‌تک',
  ARRAY['سیستم ردیابی نصب شده روی زمین', 'پلتفرم نظارت پیشرفته', 'پیکربندی متصل به شبکه', 'طراحی مقاوم در برابر آب و هوا', 'معماری مقیاس‌پذیر'],
  ARRAY['/placeholder.svg?height=300&width=400', '/placeholder.svg?height=300&width=400'],
  'greentech-commercial-solar-farm',
  true
),
(
  'مجتمع خورشیدی صنعتی - شرکت تولیدی',
  'نصب خورشیدی عظیم صنعتی که کل عملیات تولیدی را با انرژی تجدیدپذیر تامین می‌کند.',
  '/placeholder.svg?height=400&width=600',
  'industrial',
  'شیراز، ایران',
  '500 کیلووات',
  '2023-11-30',
  'شرکت تولیدی',
  ARRAY['پنل‌های درجه صنعتی', 'سیستم اینورتر سه فاز', 'تکنولوژی توازن بار', 'نظارت از راه دور', 'برنامه نگهداری'],
  ARRAY['/placeholder.svg?height=300&width=400', '/placeholder.svg?height=300&width=400'],
  'manufacturing-corp-industrial-solar',
  true
),
(
  'خانه سازگار با محیط زیست - اقامتگاه اسمیت',
  'راه‌حل خورشیدی خانه پایدار با ذخیره‌سازی باتری برای استقلال کامل انرژی.',
  '/placeholder.svg?height=400&width=600',
  'residential',
  'کرج، ایران',
  '12 کیلووات',
  '2024-02-10',
  'خانواده اسمیت',
  ARRAY['پنل‌های خورشیدی پریمیوم', 'یکپارچه‌سازی با باتری تسلا', 'راه‌اندازی اندازه‌گیری خالص', 'یکپارچه‌سازی خانه هوشمند', 'داشبورد نظارت انرژی'],
  ARRAY['/placeholder.svg?height=300&width=400', '/placeholder.svg?height=300&width=400'],
  'smith-eco-friendly-home-solar',
  true
),
(
  'نصب خورشیدی مجتمع اداری',
  'نصب خورشیدی مجتمع اداری چند ساختمانی که انرژی پاک را برای دفتر مرکزی شرکت فراهم می‌کند.',
  '/placeholder.svg?height=400&width=600',
  'commercial',
  'مشهد، ایران',
  '180 کیلووات',
  '2023-12-05',
  'شرکت راه‌حل‌های شرکتی',
  ARRAY['یکپارچه‌سازی چند ساختمانی', 'نظارت متمرکز', 'قابلیت کاهش اوج مصرف', 'پشتیبانی گواهینامه LEED', 'نصب حرفه‌ای'],
  ARRAY['/placeholder.svg?height=300&width=400', '/placeholder.svg?height=300&width=400'],
  'office-complex-solar-installation',
  true
),
(
  'پروژه خورشیدی کشاورزی - مزرعه دره سبز',
  'نصب کشاورزی-ولتائیک که تولید انرژی خورشیدی را با شیوه‌های کشاورزی پایدار ترکیب می‌کند.',
  '/placeholder.svg?height=400&width=600',
  'commercial',
  'کرمان، ایران',
  '300 کیلووات',
  '2023-10-15',
  'مزرعه دره سبز',
  ARRAY['طراحی کشاورزی-ولتائیک', 'فاصله‌گذاری مناسب برای محصول', 'یکپارچه‌سازی سیستم آبیاری', 'نظارت آب و هوا', 'بهینه‌سازی استفاده دوگانه از زمین'],
  ARRAY['/placeholder.svg?height=300&width=400', '/placeholder.svg?height=300&width=400'],
  'green-valley-agricultural-solar',
  true
);
